ALTER TABLE "calidad_desperdicio_merma" ADD FOREIGN KEY ("id_user_responsable") REFERENCES "usuario" ("id_user");

CREATE TABLE "notificaciones" (
  "id_notificacion" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tipo_notificacion" VARCHAR(50) NOT NULL,
  "mensaje" TEXT NOT NULL,
  "leido" BOOLEAN NOT NULL DEFAULT false,
  "fecha_creacion" TIMESTAMP NOT NULL DEFAULT (now()),
  "fecha_leido" TIMESTAMP,
  "metadata" JSONB,
  CONSTRAINT "chk_tipo_notificacion" CHECK (tipo_notificacion IN ('STOCK_BAJO', 'VENCIMIENTO_PROXIMO'))
);

-- Procedimiento para generar notificaciones de stock bajo
CREATE OR REPLACE FUNCTION generar_notificaciones_stock_bajo()
RETURNS void AS $$
DECLARE
    insumo_rec RECORD;
BEGIN
    -- Recorrer cada insumo que tenga el stock por debajo del mínimo
    FOR insumo_rec IN
        SELECT id_insumo, nombre, stock_actual, stock_minimo
        FROM insumo
        WHERE stock_actual < stock_minimo
    LOOP
        -- Verificar si ya existe una notificación de stock bajo no leída para este insumo
        IF NOT EXISTS (
            SELECT 1
            FROM notificaciones
            WHERE tipo_notificacion = 'STOCK_BAJO'
              AND leido = FALSE
              AND metadata->>'id_insumo' = insumo_rec.id_insumo::text
        ) THEN
            -- Si no existe, insertar la nueva notificación
            INSERT INTO notificaciones (tipo_notificacion, mensaje, metadata)
            VALUES (
                'STOCK_BAJO',
                'Alerta: El insumo "' || insumo_rec.nombre || '" tiene un stock bajo.',
                jsonb_build_object(
                    'id_insumo', insumo_rec.id_insumo,
                    'nombre_insumo', insumo_rec.nombre,
                    'stock_actual', insumo_rec.stock_actual,
                    'stock_minimo', insumo_rec.stock_minimo
                )
            );
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql;