


-- =================================================================
-- 1. MÓDULO DE SEGURIDAD (RBAC - Role-Based Access Control)
-- =================================================================

CREATE TABLE "usuario" (
  "id_user" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "apellidos" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL, -- Debe ser un HASH
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "ultimo_acceso" TIMESTAMP,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- (NUEVA) Tabla de Roles
CREATE TABLE "roles" (
  "id_rol" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre_rol" VARCHAR(100) UNIQUE NOT NULL, -- Ej: "Administrador", "Pastelero", "Almacenero"
  "descripcion" TEXT,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- (NUEVA) Tabla de enlace Usuario <-> Roles
CREATE TABLE "usuario_roles" (
  "id_usuario_rol" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_user" BIGINT NOT NULL,
  "id_rol" BIGINT NOT NULL,
  UNIQUE ("id_user", "id_rol")
);

-- Tabla de Permisos (Refactorizada: sin 'descripcion_permiso')
CREATE TABLE "permisos" (
  "id_permiso" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "modulo" VARCHAR(100) NOT NULL,
  "accion" VARCHAR(50) NOT NULL, -- Ej: "CREAR", "LEER", "ACTUALIZAR", "ELIMINAR", "APROBAR"
  UNIQUE ("modulo", "accion")
);

-- (NUEVA) Tabla de enlace Rol <-> Permisos
CREATE TABLE "roles_permisos" (
  "id_rol_permiso" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_rol" BIGINT NOT NULL,
  "id_permiso" BIGINT NOT NULL,
  UNIQUE ("id_rol", "id_permiso")
);

-- =================================================================
-- 2. MÓDULO DE CONFIGURACIÓN Y CATÁLOGOS
-- =================================================================

CREATE TABLE "empresa" (
  "id_empresa" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre_empresa" VARCHAR(255) NOT NULL,
  "ruc" VARCHAR(20) UNIQUE NOT NULL,
  "direccion" TEXT NOT NULL,
  "telefono" VARCHAR(20) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "estado" BOOLEAN NOT NULL DEFAULT true,
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "proveedores" (
  "id_proveedor" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "ruc_dni" VARCHAR(20) UNIQUE NOT NULL,
  "numero_contacto" VARCHAR(15) NOT NULL,
  "email_contacto" VARCHAR(255) NOT NULL,
  "direccion_fiscal" TEXT NOT NULL,
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- Tabla de Insumos (Refactorizada: Sin stock_actual ni precio_promedio)
CREATE TABLE "insumo" (
  "id_insumo" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "codigo" VARCHAR(50) UNIQUE NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "descripcion" TEXT,
  "unidad_medida" VARCHAR(50) NOT NULL, -- Unidad de almacenamiento (ej. 'kg', 'lt')
  "stock_minimo" DECIMAL(12,4) NOT NULL DEFAULT 0, -- Se mantiene para alertas ROP de Fase 1
  "perecible" BOOLEAN NOT NULL DEFAULT false,
  "categoria" VARCHAR(100),
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "anulado" BOOLEAN NOT NULL DEFAULT false
  -- "stock_actual" ELIMINADO
  -- "precio_promedio" ELIMINADO
);

-- Tabla de Productos Terminados (Se mantiene igual)
CREATE TABLE "productos_terminados" (
  "id_producto" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "codigo_producto" VARCHAR(50) UNIQUE NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "descripcion" TEXT,
  "unidad_medida" VARCHAR(50) NOT NULL,
  "stock_actual" DECIMAL(12,4) NOT NULL DEFAULT 0, -- El stock de productos terminados SÍ es agregado
  "stock_minimo" DECIMAL(12,4) NOT NULL DEFAULT 0,
  "vida_util_dias" INT,
  "precio_venta" DECIMAL(12,2) DEFAULT 0,
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- Tabla de Recetas (Se mantiene igual)
CREATE TABLE "recetas" (
  "id_receta" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_producto" BIGINT NOT NULL,
  "codigo_receta" VARCHAR(50) UNIQUE NOT NULL,
  "nombre_receta" VARCHAR(255) NOT NULL,
  "descripcion" TEXT,
  "rendimiento_producto_terminado" DECIMAL(12,4) NOT NULL,
  "costo_estimado" DECIMAL(12,2) DEFAULT 0, -- Será un costo de referencia
  "fecha_creacion" TIMESTAMP NOT NULL DEFAULT (now()),
  "version" DECIMAL(3,1) DEFAULT 1,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- Tabla de Detalle de Recetas (Se mantiene igual)
CREATE TABLE "recetas_detalle" (
  "id_receta_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_receta" BIGINT NOT NULL,
  "id_insumo" BIGINT NOT NULL,
  "cantidad" DECIMAL(12,4) NOT NULL, -- Cantidad en unidad de uso (ej. 'g', 'ml')
  "costo_unitario" DECIMAL(12,4) DEFAULT 0, -- Costo estimado
  "costo_total" DECIMAL(12,2) DEFAULT 0,
  "es_opcional" BOOLEAN NOT NULL DEFAULT false,
  "observaciones" TEXT
);

-- =================================================================
-- 3. MÓDULO DE COMPRAS E INVENTARIO (FEFO)
-- =================================================================

-- Tabla de Órdenes de Compra (Se mantiene igual)
CREATE TABLE "orden_de_compra" (
  "id_orden" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_orden" VARCHAR(50) UNIQUE NOT NULL,
  "id_proveedor" BIGINT NOT NULL,
  "fecha_orden" TIMESTAMP NOT NULL DEFAULT (now()),
  "fecha_entrega_esperada" TIMESTAMP NOT NULL,
  "moneda" VARCHAR(3) NOT NULL DEFAULT 'PEN',
  "tipo_cambio" DECIMAL(8,4) DEFAULT 1,
  "sub_total" DECIMAL(12,2) NOT NULL,
  "descuento" DECIMAL(12,2) DEFAULT 0,
  "igv" DECIMAL(12,2) NOT NULL DEFAULT 0,
  "total" DECIMAL(12,2) NOT NULL,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE', -- PENDIENTE, APROBADO, RECIBIDO, ANULADO
  "observaciones" TEXT,
  "id_user_creador" BIGINT NOT NULL,
  "id_user_aprobador" BIGINT,
  "fecha_aprobacion" TIMESTAMP,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- Tabla Detalle de Órdenes de Compra (Se mantiene igual)
CREATE TABLE "orden_de_compra_detalle" (
  "id_orden_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_orden" BIGINT NOT NULL,
  "id_insumo" BIGINT NOT NULL,
  "cantidad" DECIMAL(12,4) NOT NULL,
  "precio_unitario" DECIMAL(12,4) NOT NULL,
  "descuento_unitario" DECIMAL(12,4) DEFAULT 0,
  "sub_total" DECIMAL(12,2) NOT NULL,
  "observaciones" TEXT
);

-- Tabla de Ingresos (Cabecera del Lote) (RENOMBRADA)
CREATE TABLE "ingresos_insumos" (
  "id_ingreso" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_ingreso" VARCHAR(50) UNIQUE NOT NULL,
  "id_orden_compra" BIGINT, -- Puede ser nulo si es ingreso sin OC
  "numero_documento" VARCHAR(50) NOT NULL, -- Nro de Factura/Guía del proveedor
  "tipo_documento" VARCHAR(20) NOT NULL, -- FACTURA, GUIA
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "fecha_ingreso" TIMESTAMP NOT NULL,
  "fecha_documento" TIMESTAMP NOT NULL,
  "id_user" BIGINT NOT NULL,
  "id_proveedor" BIGINT NOT NULL,
  "observaciones" TEXT,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'COMPLETADO',
  "monto_total" DECIMAL(12,2) DEFAULT 0,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- Tabla Detalle de Ingresos (¡ESTA ES LA TABLA DE LOTES!) (RENOMBRADA y Refactorizada)
CREATE TABLE "ingresos_insumos_detalle" (
  "id_ingreso_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_ingreso" BIGINT NOT NULL,
  "id_insumo" BIGINT NOT NULL,
  "cantidad_ingresada" DECIMAL(12,4) NOT NULL,
  "precio_unitario" DECIMAL(12,4) NOT NULL, -- Costo Variable Real
  "subtotal" DECIMAL(12,2) NOT NULL,
  "fecha_vencimiento" TIMESTAMP, -- Para FEFO
  "cantidad_restante" DECIMAL(12,4) NOT NULL DEFAULT 0 -- ¡NUEVA COLUMNA! Stock vivo del lote.
  -- "cantidad_ordenada" ELIMINADA (ya está en orden_de_compra_detalle)
);

-- =================================================================
-- 4. MÓDULO DE MOVIMIENTOS Y TRAZABILIDAD (FEFO)
-- =================================================================

-- Tabla de Movimiento de Insumos (Kardex) (Refactorizada)
CREATE TABLE "movimiento_insumos" (
  "id_movimiento" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_movimiento" VARCHAR(50) UNIQUE NOT NULL,
  "id_insumo" BIGINT NOT NULL,
  "id_lote" BIGINT, -- ¡NUEVA COLUMNA! Enlace al lote
  "tipo_movimiento" VARCHAR(20) NOT NULL, -- ENTRADA, SALIDA
  "motivo" VARCHAR(100) NOT NULL, -- COMPRA, PRODUCCION, MERMA, AJUSTE
  "cantidad" DECIMAL(12,4) NOT NULL, -- Positivo para entradas, negativo para salidas
  "stock_anterior_lote" DECIMAL(12,4), -- Stock del lote antes del movimiento
  "stock_nuevo_lote" DECIMAL(12,4), -- Stock del lote después del movimiento
  "fecha_movimiento" TIMESTAMP NOT NULL DEFAULT (now()),
  "id_user" BIGINT NOT NULL,
  "id_documento_origen" BIGINT,
  "tipo_documento_origen" VARCHAR(50), -- Ej: 'INGRESO', 'MERMA', 'PRODUCCION'
  "observaciones" TEXT,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- Tabla de Movimiento de Productos Terminados (Kardex) (Se mantiene igual)
CREATE TABLE "movimiento_productos_terminados" (
  "id_movimiento" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_movimiento" VARCHAR(50) UNIQUE NOT NULL,
  "id_producto" BIGINT NOT NULL,
  "tipo_movimiento" VARCHAR(20) NOT NULL, -- ENTRADA, SALIDA
  "motivo" VARCHAR(100) NOT NULL, -- PRODUCCION, VENTA, MERMA
  "cantidad" DECIMAL(12,4) NOT NULL, -- Positivo para entradas, negativo para salidas
  "precio_venta" DECIMAL(12,4) DEFAULT 0,
  "fecha_movimiento" TIMESTAMP NOT NULL DEFAULT (now()),
  "id_user" BIGINT NOT NULL,
  "id_documento_origen" BIGINT,
  "tipo_documento_origen" VARCHAR(50),
  "observaciones" TEXT,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- Tabla de Mermas (Refactorizada)
CREATE TABLE "calidad_desperdicio_merma" (
  "id_merma" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_registro" VARCHAR(50) UNIQUE NOT NULL,
  "tipo" VARCHAR(50) NOT NULL, -- INSUMO, PRODUCTO_TERMINADO
  "causa" TEXT NOT NULL, -- VENCIMIENTO, ROTURA
  "cantidad" DECIMAL(12,4) NOT NULL,
  "costo_unitario" DECIMAL(12,4) DEFAULT 0, -- Se calculará desde el lote
  "costo_total" DECIMAL(12,2) DEFAULT 0,
  "fecha_caso" TIMESTAMP NOT NULL DEFAULT (now()),
  "id_insumo" BIGINT,
  "id_producto" BIGINT,
  "id_lote" BIGINT, -- ¡NUEVA COLUMNA! Enlace al lote
  "id_user_responsable" BIGINT NOT NULL,
  "observacion" TEXT,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'REGISTRADO',
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

-- =================================================================
-- 5. MÓDULO DE ALERTAS (FEFO Y ROP)
-- =================================================================

CREATE TABLE "notificaciones" (
  "id_notificacion" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tipo_notificacion" VARCHAR(50) NOT NULL,
  "mensaje" TEXT NOT NULL,
  "leido" BOOLEAN NOT NULL DEFAULT false,
  "fecha_creacion" TIMESTAMP NOT NULL DEFAULT (now()),
  "fecha_leido" TIMESTAMP,
  "metadata" JSONB,
  CONSTRAINT "chk_tipo_notificacion" CHECK (tipo_notificacion IN ('STOCK_BAJO', 'VENCIMIENTO_PROXIMO', 'MRP_COMPRA'))
);

-- =================================================================
-- 6. DEFINICIÓN DE FOREIGN KEYS
-- =================================================================

-- Seguridad
ALTER TABLE "usuario_roles" ADD FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");
ALTER TABLE "usuario_roles" ADD FOREIGN KEY ("id_rol") REFERENCES "roles" ("id_rol");
ALTER TABLE "roles_permisos" ADD FOREIGN KEY ("id_rol") REFERENCES "roles" ("id_rol");
ALTER TABLE "roles_permisos" ADD FOREIGN KEY ("id_permiso") REFERENCES "permisos" ("id_permiso");

-- Catálogos
ALTER TABLE "recetas" ADD FOREIGN KEY ("id_producto") REFERENCES "productos_terminados" ("id_producto");
ALTER TABLE "recetas_detalle" ADD FOREIGN KEY ("id_receta") REFERENCES "recetas" ("id_receta");
ALTER TABLE "recetas_detalle" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");

-- Compras (ref a Seguridad y Catálogos)
ALTER TABLE "orden_de_compra" ADD FOREIGN KEY ("id_proveedor") REFERENCES "proveedores" ("id_proveedor");
ALTER TABLE "orden_de_compra" ADD FOREIGN KEY ("id_user_creador") REFERENCES "usuario" ("id_user");
ALTER TABLE "orden_de_compra" ADD FOREIGN KEY ("id_user_aprobador") REFERENCES "usuario" ("id_user");
ALTER TABLE "orden_de_compra_detalle" ADD FOREIGN KEY ("id_orden") REFERENCES "orden_de_compra" ("id_orden");
ALTER TABLE "orden_de_compra_detalle" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");

-- Inventario/Lotes (ref a Compras, Seguridad y Catálogos)
ALTER TABLE "ingresos_insumos" ADD FOREIGN KEY ("id_orden_compra") REFERENCES "orden_de_compra" ("id_orden");
ALTER TABLE "ingresos_insumos" ADD FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");
ALTER TABLE "ingresos_insumos" ADD FOREIGN KEY ("id_proveedor") REFERENCES "proveedores" ("id_proveedor");
ALTER TABLE "ingresos_insumos_detalle" ADD FOREIGN KEY ("id_ingreso") REFERENCES "ingresos_insumos" ("id_ingreso");
ALTER TABLE "ingresos_insumos_detalle" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");

-- Movimientos/Trazabilidad (ref a Lotes, Seguridad y Catálogos)
ALTER TABLE "movimiento_insumos" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");
ALTER TABLE "movimiento_insumos" ADD FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");
ALTER TABLE "movimiento_insumos" ADD FOREIGN KEY ("id_lote") REFERENCES "ingresos_insumos_detalle" ("id_ingreso_detalle");

ALTER TABLE "movimiento_productos_terminados" ADD FOREIGN KEY ("id_producto") REFERENCES "productos_terminados" ("id_producto");
ALTER TABLE "movimiento_productos_terminados" ADD FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");

ALTER TABLE "calidad_desperdicio_merma" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");
ALTER TABLE "calidad_desperdicio_merma" ADD FOREIGN KEY ("id_producto") REFERENCES "productos_terminados" ("id_producto");
ALTER TABLE "calidad_desperdicio_merma" ADD FOREIGN KEY ("id_user_responsable") REFERENCES "usuario" ("id_user");
ALTER TABLE "calidad_desperdicio_merma" ADD FOREIGN KEY ("id_lote") REFERENCES "ingresos_insumos_detalle" ("id_ingreso_detalle");