from enum import Enum

class AreaPersonal(str, Enum):
    PRODUCCION = "PRODUCCION"
    ALMACEN = "ALMACEN"
    VENTAS = "VENTAS"
    ADMINISTRACION = "ADMINISTRACION"
    CALIDAD = "CALIDAD"
    LOGISTICA = "LOGISTICA"
    CONTABILIDAD = "CONTABILIDAD"
    RECURSOS_HUMANOS = "RECURSOS_HUMANOS"
