import enum

class EstadoEnum(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    TERMINADO = "TERMINADO"
    COMPLETADO = "COMPLETADO"
    ANULADO = "ANULADO"
    ACTIVA = "ACTIVA"
    REGISTRADO = "REGISTRADO"
    COMPLETADO = "COMPLETADO"

