from enum import Enum

class TipoModulo(str, Enum):
    USUARIOS = "USUARIOS"
    ROLES = "ROLES"
    PROVEEDORES = "PROVEEDORES"
    INSUMOS = "INSUMOS"
    PRODUCTOS = "PRODUCTOS"
    RECETAS = "RECETAS"
    COMPRAS = "COMPRAS"
    INVENTARIO = "INVENTARIO"
    PRODUCCION = "PRODUCCION"
    MERMA = "MERMA"
    REPORTES = "REPORTES"
    CONFIGURACION = "CONFIGURACION"

