"""esquema inicial

Revision ID: 82a795feb898
Revises: 
Create Date: 2025-11-14 16:33:34.453922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a795feb898'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with open('querys/shemas.sql', 'r' , encoding='utf-8-sig') as f:
        op.execute(f.read())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS "empresa", "usuario", "roles", "usuario_roles", "permisos", "roles_permisos", "proveedores", "insumo", "costo_insumos", "orden_de_compra", "orden_de_compra_detalle", "ingresos_insumos", "ingresos_insumos_detalle", "recetas", "recetas_detalle", "productos_terminados", "movimiento_insumos", "movimiento_productos_terminados", "calidad_desperdicio_merma", "notificaciones" CASCADE;')
    op.execute('DROP TYPE IF EXISTS "tipo_modulo";')
    # ### end Alembic commands ###
