"""crear_tabla_y_procedimiento_de_notificaciones

Revision ID: <TU_NUEVO_ID_DE_REVISION>
Revises: ee00bf3dd3b1
Create Date: 2025-11-05 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb689c0281d'
down_revision: Union[str, None] = 'ee00bf3dd3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Comandos para crear la tabla y el procedimiento ###

    # 1. Crear la tabla de notificaciones
    op.execute("""
        CREATE TABLE "notificaciones" (
          "id_notificacion" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
          "tipo_notificacion" VARCHAR(50) NOT NULL,
          "mensaje" TEXT NOT NULL,
          "leido" BOOLEAN NOT NULL DEFAULT false,
          "fecha_creacion" TIMESTAMP NOT NULL DEFAULT (now()),
          "fecha_leido" TIMESTAMP,
          "metadata" JSONB,
          CONSTRAINT "chk_tipo_notificacion" CHECK (tipo_notificacion IN ('STOCK_BAJO', 'VENCIMIENTO_PROXIMO'))
        );
    """)

    # 2. Crear el procedimiento almacenado para generar notificaciones
    op.execute("""
        CREATE OR REPLACE FUNCTION generar_notificaciones_stock_bajo()
        RETURNS void AS $$
        DECLARE
            insumo_rec RECORD;
        BEGIN
            -- Recorrer cada insumo que tenga el stock por debajo del mínimo
            FOR insumo_rec IN
                SELECT id_insumo, nombre, stock_actual, stock_minimo
                FROM insumo
                WHERE stock_actual < stock_minimo
            LOOP
                -- Verificar si ya existe una notificación de stock bajo no leída para este insumo
                IF NOT EXISTS (
                    SELECT 1
                    FROM notificaciones
                    WHERE tipo_notificacion = 'STOCK_BAJO'
                      AND leido = FALSE
                      AND metadata->>'id_insumo' = insumo_rec.id_insumo::text
                ) THEN
                    -- Si no existe, insertar la nueva notificación
                    INSERT INTO notificaciones (tipo_notificacion, mensaje, metadata)
                    VALUES (
                        'STOCK_BAJO',
                        'Alerta: El insumo "' || insumo_rec.nombre || '" tiene un stock bajo.',
                        jsonb_build_object(
                            'id_insumo', insumo_rec.id_insumo,
                            'nombre_insumo', insumo_rec.nombre,
                            'stock_actual', insumo_rec.stock_actual,
                            'stock_minimo', insumo_rec.stock_minimo
                        )
                    );
                END IF;
            END LOOP;
        END;
        $$ LANGUAGE plpgsql;
    """)


def downgrade() -> None:
    # ### Comandos para revertir los cambios ###

    # 1. Eliminar el procedimiento almacenado
    op.execute("DROP FUNCTION IF EXISTS generar_notificaciones_stock_bajo();")

    # 2. Eliminar la tabla de notificaciones
    op.execute("DROP TABLE IF EXISTS notificaciones;")
