CREATE TABLE "empresa" (
  "id_empresa" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre_empresa" VARCHAR(255) NOT NULL,
  "ruc" VARCHAR(20) UNIQUE NOT NULL,
  "direccion" TEXT NOT NULL,
  "telefono" VARCHAR(20) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "estado" BOOLEAN NOT NULL DEFAULT true,
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "usuario" (
  "id_user" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "es_admin" BOOLEAN NOT NULL DEFAULT false,
  "nombre" VARCHAR(255) NOT NULL,
  "apellidos" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "ultimo_acceso" TIMESTAMP,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "permisos" (
  "id_permiso" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descripcion_permiso" VARCHAR(150) NOT NULL,
  "modulo" VARCHAR(50) NOT NULL,
  "accion" VARCHAR(50) NOT NULL
);

CREATE TABLE "usuario_permisos" (
  "id_user_permiso" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_user" BIGINT NOT NULL,
  "id_permiso" BIGINT NOT NULL,
  "fecha_asignacion" TIMESTAMP NOT NULL DEFAULT (now()),
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "proveedores" (
  "id_proveedor" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "ruc_dni" VARCHAR(20) UNIQUE NOT NULL,
  "numero_contacto" VARCHAR(15) NOT NULL,
  "email_contacto" VARCHAR(255) NOT NULL,
  "direccion_fiscal" TEXT NOT NULL,
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "insumo" (
  "id_insumo" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "codigo" VARCHAR(50) UNIQUE NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "descripcion" TEXT,
  "unidad_medida" VARCHAR(50) NOT NULL,
  "stock_actual" DECIMAL(12,4) NOT NULL DEFAULT 0,
  "stock_minimo" DECIMAL(12,4) NOT NULL DEFAULT 0,
  "fecha_caducidad" TIMESTAMP,
  "perecible" BOOLEAN NOT NULL DEFAULT false,
  "precio_promedio" DECIMAL(12,4) DEFAULT 0,
  "categoria" VARCHAR(100),
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "costo_insumos" (
  "id_costo" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_insumo" BIGINT NOT NULL,
  "precio_unitario" DECIMAL(12,4) NOT NULL,
  "fecha_vigencia" TIMESTAMP NOT NULL,
  "fecha_fin" TIMESTAMP,
  "id_ingreso" BIGINT,
  "tipo_costo" VARCHAR(20) NOT NULL,
  "moneda" VARCHAR(3) NOT NULL DEFAULT 'PEN',
  "id_user" BIGINT NOT NULL,
  "observaciones" TEXT,
  "activo" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "orden_de_compra" (
  "id_orden" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_orden" VARCHAR(50) UNIQUE NOT NULL,
  "id_proveedor" BIGINT NOT NULL,
  "fecha_orden" TIMESTAMP NOT NULL DEFAULT (now()),
  "fecha_entrega_esperada" TIMESTAMP NOT NULL,
  "moneda" VARCHAR(3) NOT NULL DEFAULT 'PEN',
  "tipo_cambio" DECIMAL(8,4) DEFAULT 1,
  "sub_total" DECIMAL(12,2) NOT NULL,
  "descuento" DECIMAL(12,2) DEFAULT 0,
  "igv" DECIMAL(12,2) NOT NULL DEFAULT 0,
  "total" DECIMAL(12,2) NOT NULL,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  "observaciones" TEXT,
  "id_user_creador" BIGINT NOT NULL,
  "id_user_aprobador" BIGINT,
  "fecha_aprobacion" TIMESTAMP,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "orden_de_compra_detalle" (
  "id_orden_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_orden" BIGINT NOT NULL,
  "id_insumo" BIGINT NOT NULL,
  "cantidad" DECIMAL(12,4) NOT NULL,
  "precio_unitario" DECIMAL(12,4) NOT NULL,
  "descuento_unitario" DECIMAL(12,4) DEFAULT 0,
  "sub_total" DECIMAL(12,2) NOT NULL,
  "observaciones" TEXT
);

CREATE TABLE "ingresos_productos" (
  "id_ingreso" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_ingreso" VARCHAR(50) UNIQUE NOT NULL,
  "id_orden_compra" BIGINT NOT NULL,
  "numero_documento" VARCHAR(50) NOT NULL,
  "tipo_documento" VARCHAR(20) NOT NULL,
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "fecha_ingreso" TIMESTAMP NOT NULL,
  "fecha_documento" TIMESTAMP NOT NULL,
  "id_user" BIGINT NOT NULL,
  "id_proveedor" BIGINT NOT NULL,
  "observaciones" TEXT,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  "monto_total" DECIMAL(12,2) DEFAULT 0,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "ingresos_productos_detalle" (
  "id_ingreso_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_ingreso" BIGINT NOT NULL,
  "id_insumo" BIGINT NOT NULL,
  "cantidad_ordenada" DECIMAL(12,4) NOT NULL,
  "cantidad_ingresada" DECIMAL(12,4) NOT NULL,
  "precio_unitario" DECIMAL(12,4) NOT NULL,
  "subtotal" DECIMAL(12,2) NOT NULL,
  "fecha_vencimiento" TIMESTAMP
);

CREATE TABLE "recetas" (
  "id_receta" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_producto" BIGINT NOT NULL,
  "codigo_receta" VARCHAR(50) UNIQUE NOT NULL,
  "nombre_receta" VARCHAR(255) NOT NULL,
  "descripcion" TEXT,
  "rendimiento_producto_terminado" DECIMAL(12,4) NOT NULL,
  "costo_estimado" DECIMAL(12,2) DEFAULT 0,
  "fecha_creacion" TIMESTAMP NOT NULL DEFAULT (now()),
  "version" DECIMAL(3,1) DEFAULT 1,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "recetas_detalle" (
  "id_receta_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_receta" BIGINT NOT NULL,
  "id_insumo" BIGINT NOT NULL,
  "cantidad" DECIMAL(12,4) NOT NULL,
  "costo_unitario" DECIMAL(12,4) DEFAULT 0,
  "costo_total" DECIMAL(12,2) DEFAULT 0,
  "es_opcional" BOOLEAN NOT NULL DEFAULT false,
  "observaciones" TEXT
);

CREATE TABLE "productos_terminados" (
  "id_producto" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "codigo_producto" VARCHAR(50) UNIQUE NOT NULL,
  "nombre" VARCHAR(255) NOT NULL,
  "descripcion" TEXT,
  "unidad_medida" VARCHAR(50) NOT NULL,
  "stock_actual" DECIMAL(12,4) NOT NULL DEFAULT 0,
  "stock_minimo" DECIMAL(12,4) NOT NULL DEFAULT 0,
  "vida_util_dias" INT,
  "precio_venta" DECIMAL(12,2) DEFAULT 0,
  "fecha_registro" TIMESTAMP NOT NULL DEFAULT (now()),
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "movimiento_insumos" (
  "id_movimiento" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_movimiento" VARCHAR(50) UNIQUE NOT NULL,
  "id_insumo" BIGINT NOT NULL,
  "tipo_movimiento" VARCHAR(20) NOT NULL,
  "motivo" VARCHAR(100) NOT NULL,
  "cantidad" DECIMAL(12,4) NOT NULL,
  "stock_anterior" DECIMAL(12,4) NOT NULL,
  "stock_nuevo" DECIMAL(12,4) NOT NULL,
  "fecha_movimiento" TIMESTAMP NOT NULL DEFAULT (now()),
  "id_user" BIGINT NOT NULL,
  "id_documento_origen" BIGINT,
  "tipo_documento_origen" VARCHAR(50),
  "observaciones" TEXT,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "movimiento_productos_terminados" (
  "id_movimiento" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_movimiento" VARCHAR(50) UNIQUE NOT NULL,
  "id_producto" BIGINT NOT NULL,
  "tipo_movimiento" VARCHAR(20) NOT NULL,
  "motivo" VARCHAR(100) NOT NULL,
  "cantidad" DECIMAL(12,4) NOT NULL,
  "precio_venta" DECIMAL(12,4) DEFAULT 0,
  "fecha_movimiento" TIMESTAMP NOT NULL DEFAULT (now()),
  "id_user" BIGINT NOT NULL,
  "id_documento_origen" BIGINT,
  "tipo_documento_origen" VARCHAR(50),
  "observaciones" TEXT,
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "calidad_desperdicio_merma" (
  "id_merma" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero_registro" VARCHAR(50) UNIQUE NOT NULL,
  "tipo" VARCHAR(50) NOT NULL,
  "causa" TEXT NOT NULL,
  "cantidad" DECIMAL(12,4) NOT NULL,
  "costo_unitario" DECIMAL(12,4) DEFAULT 0,
  "costo_total" DECIMAL(12,2) DEFAULT 0,
  "fecha_caso" TIMESTAMP NOT NULL DEFAULT (now()),
  "id_insumo" BIGINT,
  "id_producto" BIGINT,
  "id_user_responsable" BIGINT NOT NULL,
  "observacion" TEXT,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'REGISTRADO',
  "anulado" BOOLEAN NOT NULL DEFAULT false
);

ALTER TABLE "usuario_permisos" ADD FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");

ALTER TABLE "usuario_permisos" ADD FOREIGN KEY ("id_permiso") REFERENCES "permisos" ("id_permiso");

ALTER TABLE "costo_insumos" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");

ALTER TABLE "costo_insumos" ADD FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");

ALTER TABLE "costo_insumos" ADD FOREIGN KEY ("id_ingreso") REFERENCES "ingresos_productos" ("id_ingreso");

ALTER TABLE "orden_de_compra" ADD FOREIGN KEY ("id_proveedor") REFERENCES "proveedores" ("id_proveedor");

ALTER TABLE "orden_de_compra" ADD FOREIGN KEY ("id_user_creador") REFERENCES "usuario" ("id_user");

ALTER TABLE "orden_de_compra" ADD FOREIGN KEY ("id_user_aprobador") REFERENCES "usuario" ("id_user");

ALTER TABLE "orden_de_compra_detalle" ADD FOREIGN KEY ("id_orden") REFERENCES "orden_de_compra" ("id_orden");

ALTER TABLE "orden_de_compra_detalle" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");

ALTER TABLE "ingresos_productos" ADD FOREIGN KEY ("id_orden_compra") REFERENCES "orden_de_compra" ("id_orden");

ALTER TABLE "ingresos_productos" ADD FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");

ALTER TABLE "ingresos_productos" ADD FOREIGN KEY ("id_proveedor") REFERENCES "proveedores" ("id_proveedor");

ALTER TABLE "ingresos_productos_detalle" ADD FOREIGN KEY ("id_ingreso") REFERENCES "ingresos_productos" ("id_ingreso");

ALTER TABLE "ingresos_productos_detalle" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");

ALTER TABLE "recetas_detalle" ADD FOREIGN KEY ("id_receta") REFERENCES "recetas" ("id_receta");

ALTER TABLE "recetas_detalle" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");

ALTER TABLE "recetas" ADD FOREIGN KEY ("id_producto") REFERENCES "productos_terminados" ("id_producto");

ALTER TABLE "movimiento_insumos" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");

ALTER TABLE "movimiento_insumos" ADD FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");

ALTER TABLE "movimiento_productos_terminados" ADD FOREIGN KEY ("id_producto") REFERENCES "productos_terminados" ("id_producto");

ALTER TABLE "movimiento_productos_terminados" ADD FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");

ALTER TABLE "calidad_desperdicio_merma" ADD FOREIGN KEY ("id_insumo") REFERENCES "insumo" ("id_insumo");

ALTER TABLE "calidad_desperdicio_merma" ADD FOREIGN KEY ("id_producto") REFERENCES "productos_terminados" ("id_producto");

ALTER TABLE "calidad_desperdicio_merma" ADD FOREIGN KEY ("id_user_responsable") REFERENCES "usuario" ("id_user");
